#EvocatioPersonaBundle_Persona:
#    resource: "@EvocatioPersonaBundle/Controller/PersonaController.php"
#    type:     annotation
#    prefix: /{_locale}/
#    requirements:
#        discriminator:  "persona"
   
    
EvocatioPersonaBundle_Person:
    resource: "@EvocatioPersonaBundle/Controller/PersonController.php"
    type:     annotation
    prefix: /{_locale}/
    defaults:  { discriminator: person, admin: admin }
    requirements:
        persona:  "person|personne"
        
EvocatioPersonaBundle_Company:
    resource: "@EvocatioPersonaBundle/Controller/CompanyController.php"
    type:     annotation
    prefix: /{_locale}/
    defaults:  { discriminator: company, admin: admin }
    requirements:
        persona:  "company|entreprise"