#EvocatioPersonaBundle_Persona:
#    resource: "@EvocatioPersonaBundle/Controller/PersonaController.php"
#    type:     annotation
#    prefix: /{_locale}/
#    requirements:
#        discriminator:  "persona"
   
    
EvocatioPersonaBundle_Person:
    resource: "@EvocatioPersonaBundle/Controller/PersonController.php"
    type:     annotation
    prefix: /{_locale}/
    defaults:
        discriminator: person
        admin: admin
    requirements:
        persona:  "person|personne"
        admin:    "admin"
        edit:     "edit|editer"
        list:     "list|lister"
        show:     "show|afficher"
        create:   "create|creer"
        
#EvocatioPersonaBundle_Company:
#    resource: "@EvocatioPersonaBundle/Controller/CompanyController.php"
#    type:     annotation
#    prefix: /{_locale}/
#    defaults:  { discriminator: company}
#    requirements:
#        persona:  "company|entreprise"