services:
  evocatio_persona.persona.read_handler:
      class:     Evocatio\Bundle\PersonaBundle\Lib\Handler\PersonaReadHandler
      arguments: ["@doctrine.orm.entity_manager", "@security.context"]
      
  evocatio_persona.persona.persistence_handler:
      class:     Evocatio\Bundle\PersonaBundle\Lib\Handler\PersonaPersistenceHandler
      arguments: ["@evocatio_persona.persona.read_handler", "@doctrine.orm.entity_manager", "@security.context"]

  evocatio_persona.persona.form_handler:
      class:     Evocatio\Bundle\PersonaBundle\Lib\Handler\PersonaFormHandler
      arguments: ["@evocatio_persona.persona.read_handler", "@security.context", "@form.factory"]
