services:
  evocatio_portfolio.project.read_handler:
      class:     Evocatio\Bundle\PortfolioBundle\Lib\Handler\ProjectReadHandler
      arguments: ["@doctrine.orm.entity_manager", "@security.context"]
      
  evocatio_portfolio.project.persistence_handler:
      class:     Evocatio\Bundle\PortfolioBundle\Lib\Handler\ProjectPersistenceHandler
      arguments: ["@evocatio_portfolio.project.read_handler", "@doctrine.orm.entity_manager", "@security.context"]

  evocatio_portfolio.project.form_handler:
      class:     Evocatio\Bundle\PortfolioBundle\Lib\Handler\ProjectFormHandler
      arguments: ["@evocatio_portfolio.project.read_handler", "@security.context", "@form.factory"]
    