services:
  portfolio.read_handler:
      class:     Evocatio\Bundle\PortfolioBundle\Lib\Handler\PortfolioReadHandler
      arguments: ["@doctrine.orm.entity_manager", "@security.context"]
      
  portfolio.persistence_handler:
      class:     Evocatio\Bundle\PortfolioBundle\Lib\Handler\PortfolioPersistenceHandler
      arguments: ["@portfolio.read_handler", "@doctrine.orm.entity_manager", "@security.context"]

  portfolio.form_handler:
      class:     Evocatio\Bundle\PortfolioBundle\Lib\Handler\PortfolioFormHandler
      arguments: ["@portfolio.read_handler", "@security.context", "@form.factory"]
      
  sheet.read_handler:
      class:     Evocatio\Bundle\PortfolioBundle\Lib\Handler\SheetReadHandler
      arguments: ["@doctrine.orm.entity_manager", "@security.context"]
      
  sheet.persistence_handler:
      class:     Evocatio\Bundle\PortfolioBundle\Lib\Handler\SheetPersistenceHandler
      arguments: ["@sheet.read_handler", "@doctrine.orm.entity_manager", "@security.context"]

  sheet.form_handler:
      class:     Evocatio\Bundle\PortfolioBundle\Lib\Handler\SheetFormHandler
      arguments: ["@sheet.read_handler", "@security.context", "@form.factory"]
    