apoge_site:
    resource: "@ApogeSiteBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/
    
apoge_site_login:
    resource: "@ApogeSiteBundle/Controller/LoginController.php"
    type:     annotation
    prefix:   /

    
#owner_site_menu_showmenulink:
#    path:  /{_locale}/{slug}
#    defaults: { _controller: HavenCmsBundle:Menu:showMenuLink }
#    requirements:  
#        slug : .+
#    methods:  [GET]

