
#redirect / to /admin/lister/page c'était en autre pour un exemple de redirect pris ici : http://symfony.com/doc/current/cookbook/routing/redirect_in_config.html
root:
    path:     /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /fr/admin/lister/page
        permanent: true

evocatio_portfolio:
    resource: "@EvocatioPortfolioBundle/Controller/"
    type:     annotation
    prefix:   /

#OwnerSiteBundle:
#    resource: "@OwnerSiteBundle/Resources/config/routing.yml"
    
#    
#WebsiteSiteBundle_ProductAdmin:
#    resource: "@WebsiteSiteBundle/Controller/ProductAdminController.php"
#    type:     annotation
#    prefix: /{_locale}/admin/product/
#    
#WebsiteSiteBundle_ProductView:
#    resource: "@WebsiteSiteBundle/Controller/ProductViewController.php"
#    type:     annotation
#    prefix: /{_locale}/product/
#    

    
# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
