website_site:
    resource: "@WebsiteSiteBundle/Controller/"
    type:     annotation
    prefix:   /
    
WebsiteSiteBundle_Faq:
    resource: "@WebsiteSiteBundle/Controller/FaqController.php"
    type:     annotation
    prefix: /{_locale}/faq/
    
WebsiteSiteBundle_Post:
    resource: "@WebsiteSiteBundle/Controller/PostController.php"
    type:     annotation
    prefix: /{_locale}/post/
    
WebsiteSiteBundle_User:
    resource: "@WebsiteSiteBundle/Controller/UserController.php"
    type:     annotation
    prefix: /{_locale}/user/
    
WebsiteSiteBundle_PosGenericProduct:
    resource: "@WebsiteSiteBundle/Controller/GenericProductController.php"
    type:     annotation
    prefix: /{_locale}/generic/
# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
