#EvocatioPosBundle:
#    resource: "@EvocatioPosBundle/Controller/"
#    type:     annotation
#    prefix:   /product

EvocatioSecurityBundle:
    resource: "@EvocatioSecurityBundle/Controller/"
    type:     annotation
    prefix: /{_locale}/auth

#EvocatioPersonaBundle:
#    resource: "@EvocatioPersonaBundle/Controller/"
#    type:     annotation
#    prefix: contact

EvocatioFaqBundle:
    resource: "@EvocatioFaqBundle/Controller/DefaultController.php"
    type:     annotation
    prefix: /{_locale}/faq
    requirements: 
      _locale: fr|en

EvocatioPostBundle:
    resource: "@EvocatioPostBundle/Controller/DefaultController.php"
    type:     annotation
    prefix: /{_locale}/post
    requirements: 
      _locale: fr|en

EvocatioCoreBundle:
    resource: "@EvocatioCoreBundle/Controller/"
    type:     annotation
    prefix: /{_locale}/core

_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   /_configurator

_main:
    resource: routing.yml
