evocatio_cms:
    resource: "@EvocatioCmsBundle/Controller/"
    type:     annotation
    prefix:   /

OwnerSiteBundle:
    resource: "@OwnerSiteBundle/Resources/config/routing.yml"
    
#    
#WebsiteSiteBundle_ProductAdmin:
#    resource: "@WebsiteSiteBundle/Controller/ProductAdminController.php"
#    type:     annotation
#    prefix: /{_locale}/admin/product/
#    
#WebsiteSiteBundle_ProductView:
#    resource: "@WebsiteSiteBundle/Controller/ProductViewController.php"
#    type:     annotation
#    prefix: /{_locale}/product/
#    

    
# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
