#EvocatioPosBundle:
#    resource: "@EvocatioPosBundle/Controller/"
#    type:     annotation
#    prefix:   /product

#EvocatioLogin:
#    resource: "@EvocatioSecurityBundle/Controller/LoginController.php"
#    type:     annotation
#    prefix: /auth/

#EvocatioUser:
#    resource: "@EvocatioSecurityBundle/Controller/UserController.php"
#    type:     annotation
#    prefix: /{_locale}/user/

EvocatioBasket:
    resource: "@EvocatioPosBundle/Controller/BasketController.php"
    type:     annotation
    prefix: /{_locale}/basket/

EvocatioPurchase:
    resource: "@EvocatioPosBundle/Controller/PurchaseController.php"
    type:     annotation
    prefix: /{_locale}/purchase/

EvocatioPosGenericProduct:
    resource: "@EvocatioPosBundle/Controller/GenericProductController.php"
    type:     annotation
    prefix: /{_locale}/generic/

EvocatioPersonaBundle:
    resource: "@EvocatioPersonaBundle/Controller/PersonaController.php"
    type:     annotation
    prefix: /{_locale}/persona/

EvocatioPersonaPerson:
    resource: "@EvocatioPersonaBundle/Controller/PersonController.php"
    type:     annotation
    prefix: /{_locale}/person/

EvocatioPersonaPersonWithCoor:
    resource: "@EvocatioPersonaBundle/Controller/PersonWithCoorController.php"
    type:     annotation
    prefix: /{_locale}/personWithCoor/

EvocatioCompanyBundle:
    resource: "@EvocatioPersonaBundle/Controller/CompanyController.php"
    type:     annotation
    prefix: /{_locale}/company/

EvocatioPostalBundle:
    resource: "@EvocatioPersonaBundle/Controller/PostalController.php"
    type:     annotation
    prefix: /{_locale}/postal/

#EvocatioFaqBundle:
#    resource: "@EvocatioFaqBundle/Controller/FaqController.php"
#    type:     annotation
#    prefix: /{_locale}/faq/
#    requirements: 
#      _locale: fr|en

#EvocatioPostBundle:
#    resource: "@EvocatioPostBundle/Controller/PostController.php"
#    type:     annotation
#    prefix: /{_locale}/post/
#    requirements: 
#      _locale: fr|en

EvocatioCoreBundle:
    resource: "@EvocatioCoreBundle/Controller/"
    type:     annotation
    prefix: /{_locale}/core/

_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   /_configurator

_main:
    resource: routing.yml
