imports:
    - { resource: "@EvocatioCoreBundle/Resources/config/services.yml" }
    - { resource: "@EvocatioWebBundle/Resources/config/services.yml" }
    - { resource: "@EvocatioPersonaBundle/Resources/config/services.yml" }