<?php

namespace Evocatio\Bundle\FaqBundle\Entity;

use Doctrine\ORM\EntityRepository;

use Evocatio\Bundle\CoreBundle\Generic\StatusRepository;

/**
 * Evocatio\Bundle\FaqBundle\Entity\FaqRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FaqRepository extends StatusRepository {

    public function findAllOnlines(){
        $query_builder = $this->createQueryBuilder('e');
        $query_builder = $this->filterOnlines($query_builder);

        return $query_builder->getQuery()->getResult();
    }
}