<?php

namespace Evocatio\Bundle\FaqBundle\Entity;

use Doctrine\ORM\EntityRepository;

use Evocatio\Bundle\CoreBundle\Generic\StatusRepository;

/**
 * Evocatio\Bundle\FaqBundle\Entity\FaqRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FaqRepository extends StatusRepository {

}