EvocatioWebBundle_Faq:
    resource: "@EvocatioWebBundle/Controller/FaqController.php"
    type:     annotation
    prefix: /{_locale}/
    defaults:
      admin: admin
    requirements:
      admin:    "admin"
      edit:     "edit|editer"
      list:     "list|lister"
      show:     "show|afficher"
      create:   "create|creer"
      _locale: fr|en
    
EvocatioWebBundle_Post:
    resource: "@EvocatioWebBundle/Controller/PostController.php"
    type:     annotation
    prefix: /{_locale}/
    requirements: 
      _locale: fr|en