evocatio_mediabundle:
    resource: "@EvocatioMediaBundle/Controller"
    type:     annotation
    prefix: /{_locale}/
    requirements:
      _locale: fr|en


#EvocatioWebBundle_Post:
#    resource: "@EvocatioWebBundle/Controller/PostController.php"
#    type:     annotation
#    prefix: /{_locale}/
#    defaults:
#      admin: admin
#    requirements:
#      _locale: fr|en