services:
  evocatio_web.faq.read_handler:
      class:     Evocatio\Bundle\WebBundle\Lib\Handler\FaqReadHandler
      arguments: ["@doctrine.orm.entity_manager", "@security.context"]
      
  evocatio_web.faq.persistence_handler:
      class:     Evocatio\Bundle\WebBundle\Lib\Handler\FaqPersistenceHandler
      arguments: ["@evocatio_web.faq.read_handler", "@doctrine.orm.entity_manager", "@security.context"]

  evocatio_web.faq.form_handler:
      class:     Evocatio\Bundle\WebBundle\Lib\Handler\FaqFormHandler
      arguments: ["@evocatio_web.faq.read_handler", "@security.context", "@form.factory"]
      
  evocatio_web.post.persistence_handler:
      class:     Evocatio\Bundle\WebBundle\Lib\Handler\PostPersistenceHandler
      arguments: ["@evocatio_web.post.read_handler", "@doctrine.orm.entity_manager", "@security.context"]
      
  evocatio_web.post.read_handler:
      class:     Evocatio\Bundle\WebBundle\Lib\Handler\PostReadHandler
      arguments: ["@doctrine.orm.entity_manager", "@security.context"]

  evocatio_web.post.form_handler:
      class:     Evocatio\Bundle\WebBundle\Lib\Handler\PostFormHandler
      arguments: ["@evocatio_web.post.read_handler", "@security.context", "@form.factory"]
    