services:
  faq.read_handler:
      class:     Evocatio\Bundle\WebBundle\Lib\FaqReadHandler
      arguments: ["@doctrine.orm.entity_manager", "@security.context"]

  faq.form_handler:
      class:     Evocatio\Bundle\WebBundle\Lib\FaqFormHandler
      arguments: ["@faq.read_handler", "@language.read_handler", "@security.context", "@form.factory"]
    