services:
  language.read_handler:
        class:     Evocatio\Bundle\CoreBundle\Lib\LanguageReadHandler
        arguments: ["@doctrine.orm.entity_manager", "@security.context"]
        
  language.persistence_handler:
        class:     Evocatio\Bundle\CoreBundle\Lib\LanguagePersistenceHandler
        arguments: ["@language.read_handler", "@doctrine.orm.entity_manager", "@security.context"]

  language.form_handler:
      class:     Evocatio\Bundle\CoreBundle\Lib\LanguageFormHandler
      arguments: ["@language.read_handler", "@security.context", "@form.factory"]
      
  culture.read_handler:
        class:     Evocatio\Bundle\CoreBundle\Lib\CultureReadHandler
        arguments: ["@doctrine.orm.entity_manager", "@security.context"]
        
  culture.persistence_handler:
        class:     Evocatio\Bundle\CoreBundle\Lib\CulturePersistenceHandler
        arguments: ["@culture.read_handler", "@language.read_handler", "@doctrine.orm.entity_manager", "@security.context"]

  culture.form_handler:
      class:     Evocatio\Bundle\CoreBundle\Lib\CultureFormHandler
      arguments: ["@culture.read_handler", "@language.read_handler", "@security.context", "@form.factory"]
      
  notifier:
      class:     Evocatio\Bundle\CoreBundle\Lib\Notifier
      arguments: ["@mailer", "@templating", "%notification_from%", "%notification_to%"]
      
  slugifier:
      class:     Evocatio\Bundle\CoreBundle\Lib\Slugifier
      
  request_modifier:
      class:     Evocatio\Bundle\CoreBundle\Lib\RequestModifier
      arguments: ["@slugifier"]