<?php

namespace Evocatio\Bundle\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Evocatio\Bundle\CoreBundle\Generic\StatusRepository;

/**
 * Evocatio\Bundle\CoreBundle\Entity\CultureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CultureRepository extends StatusRepository {

    public function createNewEntity($symbol = null, $language = null, $status = null) {
        $entity = new Culture();
        $entity->setSymbol($symbol);
        $entity->setStatus($status);
        $entity->setLanguage($language);

        return $entity;
    }

}