<?php

namespace Evocatio\Bundle\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

use Evocatio\Bundle\CoreBundle\Generic\StatusRepository;

/**
 * Evocatio\Bundle\FaqBundle\Entity\LanguageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LanguageRepository extends EntityRepository {
    
    public function createNewEntity($symbol = null, $status = 0){
        $entity = new Language();
        $entity->setStatus($status);
        $entity->setSymbol($symbol);
        
        return $entity;
    }

}