<?php

namespace tahua\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CmsPageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CmsPageAccueilRepository extends CmsPageRepository
{
}