<?php

namespace Evocatio\Bundle\CmsBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Evocatio\Bundle\CmsBundle\Entity\PageTranslation;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends EntityRepository {

    public function findByLocalizedSlug($slug, $language) {
        $query_builder = $this->createBaseQueryBuilder();
        $this->filterByLang($language, $query_builder);
        $this->filterBySlug($slug, $query_builder);
        $this->filterTranslationByStatus(PageTranslation::STATUS_PUBLISHED, $query_builder);

        return $query_builder->getQuery()->getOneOrNullResult();
    }

    private function filterTranslationByStatus($status, $qb = null) {
        $this->query_builder = ($qb) ? $qb : $this->createBaseQueryBuilder();

        $this->query_builder->andWhere("t.status = :status");
        $this->query_builder->setParameter("status", $status);

        return $this;
    }

    private function filterBySlug($slug, $qb = null) {
        $this->query_builder = ($qb) ? $qb : $this->createBaseQueryBuilder();

        $this->query_builder->andWhere("t.slug = :slug");
        $this->query_builder->setParameter("slug", $slug);

        return $this;
    }

    private function filterByLang($lang, $qb = null) {
        $this->query_builder = ($qb) ? $qb : $this->createBaseQueryBuilder();

        $this->query_builder
                ->leftJoin("t.trans_lang", "tl")
                ->andWhere("tl.symbol= :language")
                ->setParameter("language", $lang)
        ;
        return $this;
    }

    public function createBaseQueryBuilder() {
        return $this->createQueryBuilder("e")
                        ->leftJoin("e.translations", "t")
        ;
    }

}
