<?php

namespace Evocatio\Bundle\CmsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends EntityRepository
{
    public function findByLocalizedSlug($slug, $language){
        $query_builder = $this->createQueryBuilder("p")
                      ->leftJoin("p.translations", "t")
                      ->leftJoin("t.trans_lang", "tl")
                      ->andWhere("tl.symbol= :language")
                      ->andWhere("t.slug = :slug")
                      ->setParameter("slug", $slug)
                      ->setParameter("language", $language)
//                      ->setParameter("page_name", $page_name)
                      ;
        $page = $query_builder->getQuery()->getOneOrNullResult();
        
        return $page;       
    }
}
