services:
  evocatio_media.file.read_handler:
      class:     Evocatio\Bundle\MediaBundle\Lib\Handler\FileReadHandler
      arguments: ["@doctrine.orm.entity_manager", "@security.context"]
      
  evocatio_media.file.persistence_handler:
      class:     Evocatio\Bundle\MediaBundle\Lib\Handler\FilePersistenceHandler
      arguments: ["@evocatio_media.file.read_handler", "@doctrine.orm.entity_manager", "@security.context", "@evocatio_media.file.manipulator"]

  evocatio_media.file.form_handler:
      class:     Evocatio\Bundle\MediaBundle\Lib\Handler\FileFormHandler
      arguments: ["@evocatio_media.file.read_handler", "@security.context", "@form.factory"]

  evocatio_media.file.manipulator:
      class:     Evocatio\Bundle\MediaBundle\Lib\Manipulator\FileManipulator
      arguments:    [%kernel.root_dir%, %secure_upload_dir%]
    
  evocatio_media.image_file.form_handler:
      class:     Evocatio\Bundle\MediaBundle\Lib\Handler\ImageFileFormHandler
      arguments: ["@evocatio_media.file.read_handler", "@security.context", "@form.factory"]
      
  evocatio_media.image_file.manipulator:
      class:     Evocatio\Bundle\MediaBundle\Lib\Manipulator\ImageFileManipulator
      arguments:    [%kernel.root_dir%, %secure_upload_dir%]