services:
  evocatio_pos.product.persistence_handler:
      class:     Evocatio\Bundle\PosBundle\Lib\Handler\ProductPersistenceHandler
      arguments: ["@evocatio_pos.product.read_handler", "@doctrine.orm.entity_manager", "@security.context"]
      
  evocatio_pos.product.read_handler:
      class:     Evocatio\Bundle\PosBundle\Lib\Handler\ProductReadHandler
      arguments: ["@doctrine.orm.entity_manager", "@security.context"]

  evocatio_pos.product.form_handler:
      class:     Evocatio\Bundle\PosBundle\Lib\Handler\ProductFormHandler
      arguments: ["@evocatio_pos.product.read_handler", "@security.context", "@form.factory"]
    