<?php

namespace Evocatio\Bundle\PosBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OrderTaxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderTaxRepository extends EntityRepository
{
}