<?php

namespace Evocatio\Bundle\PosBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Evocatio\Bundle\CoreBundle\Generic\StatusRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends StatusRepository
{

//	public function getProductsOrderByCategory()
//    {
//        $query = $this->getEntityManager()
//                ->createQuery('SELECT p FROM tahuaSiteBundle:Product p
//                    JOIN p.category c WHERE c.id = p.category AND p.Actif=1 AND ORDER BY c.id ASC');
//        
//
//        return $query->getResult();
//    }
//
//	public function getProductDesc($id)
//    {
//        $query = $this->getEntityManager()
//                ->createQuery('SELECT p FROM tahuaSiteBundle:Product p
//                     WHERE p.id='.$id.'');
//        //$query->setParameter(1, $category->getId());
//
//        return $query->getResult();
//    }
//
//	public function getProduistAll()
//    {
//        $query = $this->getEntityManager()
//                ->createQuery('SELECT p FROM tahuaSiteBundle:Product p
//                     ORDER BY p.Titre');
//        //$query->setParameter(1, $category->getId());
//
//        return $query->getResult();
//    }
//
//    public function getProductsOrderByCategoryAdmin()
//    {
//        $query = $this->getEntityManager()
//                ->createQuery('SELECT p FROM tahuaSiteBundle:Product p
//                    JOIN p.category c WHERE c.id = p.category    ORDER BY c.id ASC');
//        return $query->getResult();
//    }
//    
//    public function getProductByIdForCurrentLang($id){
//        $lang = \Locale::getPrimaryLanguage(\Locale::getDefault());
//        $em = $this->getEntityManager();
//        $query = $em->createQuery("SELECT p, pt FROM tahuaSiteBundle:Product p JOIN p.translations pt WHERE p.id = ". $id. " AND pt.lang LIKE '". $lang . "'");
////        return 'bogus';
//        
////        return $query;
//        return $query->getSingleResult();
//    }
//
//    public function getPrixForProductById($id){
//        $em = $this->getEntityManager();
//        $query = $em->createQuery("SELECT p FROM tahuaSiteBundle:Product p  WHERE p.id = ". $id);
//        return $query->getSingleResult();
//    }
//
//    public function findAllWhereIdIn($ids){
//        $lang = \Locale::getPrimaryLanguage(\Locale::getDefault());
//        $em = $this->getEntityManager();
//        $query = $em->createQuery("SELECT p, pt FROM tahuaSiteBundle:Product p JOIN p.translations pt WHERE p.id in ". $ids. " AND pt.lang LIKE '". $lang . "'");
//
//        return $query->getResult();
//    }

}
