<?php

namespace Evocatio\Bundle\PosBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TaxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaxRepository extends EntityRepository
{

}