<?php

namespace Evocatio\Bundle\WebBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Evocatio\Bundle\CoreBundle\Generic\StatusRepository;

/**
 * Evocatio\Bundle\WebBundle\Entity\FaqRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FaqRepository extends StatusRepository {

    private $query_builder;

    public function getQueryBuilder() {
        return $this->query_builder;
    }

    public function setQueryBuilder(\Doctrine\ORM\QueryBuilder $query_builder) {
        $this->query_builder = $query_builder;
    }

    public function findAll($status = null, $return_result = true) {

        $this->query_builder = $this->createQueryBuilder("d");

        if (!is_null($status))
            $this->query_builder = $this->filterByStatus($status, false)->getQueryBuilder();

        return ($return_result) ? $this->getResult() : $this;
    }

    private function filterByStatus($status, $return_result = true) {

        if (is_null($this->query_builder))
            $this->query_builder = $this->findAll();

        $this->query_builder->andWhere("d.status in (:status)");
        $this->query_builder->setParameter("status", $status);

        return ($return_result) ? $this->getResult() : $this;
    }

    public function getResult() {
        $query = $this->query_builder->getQuery();
        return $query->getResult();
    }

}