<?php

namespace Evocatio\Bundle\WebBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Evocatio\Bundle\CoreBundle\Generic\StatusRepository;
use Evocatio\Bundle\WebBundle\Entity\Faq;

/**
 * Evocatio\Bundle\WebBundle\Entity\FaqRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FaqRepository extends StatusRepository {

    private $query_builder;

    public function getQueryBuilder() {
        return $this->query_builder;
    }

    public function setQueryBuilder(\Doctrine\ORM\QueryBuilder $query_builder) {
        $this->query_builder = $query_builder;
    }

    public function findAll() {
        $this->query_builder = $this->createBaseBuilder();
        return $this->getResult();
    }

    public function findAllPublished() {
        $this->query_builder = $this->filterByStatus(Faq::STATUS_PUBLISHED)->getQueryBuilder();
        return $this->getResult();
    }

    private function filterByStatus($status) {
        if (is_null($this->query_builder))
            $this->query_builder = $this->createBaseBuilder();

        $this->query_builder->andWhere("e.status = :status");
        $this->query_builder->setParameter("status", $status);

        return $this;
    }

    public function createBaseBuilder() {
        $this->query_builder = $this->createQueryBuilder("e");
        return $this->query_builder->select("e, t")
                        ->leftJoin("e.translations", "t");
    }

    public function getResult() {
        $query = $this->query_builder->getQuery();
        return $query->getResult();
    }

}